GitVersion.yml
- changed the gitversion to CD to enable prerelease tag on master 
=> switching gitversion mode to cd

.build/tasks/New-Release.GitHub.build.ps1, CHANGELOG.md, azure-pipelines.yml, build.yaml
- GitHub publish Release in AzDO yaml when master & test success
=> Adding GitHub Release

.build/tasks/Invoke-Pester.pester.build.ps1, .build/tasks/New-Release.GitHub.build.ps1, GitVersion.yml
- changed the gitversion increment & mode to CD
=> Changing Gitversion to CD & increment

.build/tasks/Build-Module.ModuleBuilder.build.ps1, GitVersion.yml, Sampler/assets/build.yaml, build.yaml
=> ModuleVersion tag grooming

.build/tasks/Invoke-Pester.pester.build.ps1
=> fixing test results asserts when decoupled from $Script: session

.build/tasks/Invoke-Pester.pester.build.ps1
=> fixing $ModuleVersion assignment in test tasks

GitVersion.yml
=> added tag to master

.build/tasks/New-Release.GitHub.build.ps1, .build/tasks/release.nuget.build.ps1, CHANGELOG.md, GitVersion.yml, RequiredModules.psd1, azure-pipelines.yml, build.yaml
=> updating publish tasks

.build/tasks/New-Release.GitHub.build.ps1, GitVersion.yml
=> Fix module manifest resolution in github release

.build/tasks/release.module.build.ps1, GitVersion.yml
=> fix publish param set

GitVersion.yml
=> updating next version to fix gitversion issue

.build/tasks/release.module.build.ps1, GitVersion.yml
=> Test fix modulepath when publishing

.build/tasks/Invoke-Pester.pester.build.ps1, .build/tasks/New-Release.GitHub.build.ps1, .build/tasks/release.module.build.ps1, CHANGELOG.md, GitVersion.yml, tests/QA/module.tests.ps1
=> Fix issue #22 prerelease tag & add changelog test

CHANGELOG.md, GitVersion.yml
=> and moving back again to a CD mode for gitversion

CHANGELOG.md, GitVersion.yml, azure-pipelines.yml
=> add branch trigger & Continuous delivery

.build/tasks/GitHubRelease.functions.ps1, CHANGELOG.md
=> fixing add assets to GH release

CHANGELOG.md, azure-pipelines.yml
- Changed the Tags trigger to include "v*" but still exclude "*-*"
=> updating AzDO trigger for tags

.build/tasks/GitHubRelease.functions.ps1, .build/tasks/New-Release.GitHub.build.ps1, CHANGELOG.md, azure-pipelines.yml, build.yaml
=> Adding Pull Request for Changelog feature

CHANGELOG.md, azure-pipelines.yml
=> switching back to normal jobs

.build/tasks/New-Release.GitHub.build.ps1, CHANGELOG.md, build.yaml
=> trying to fix weird Changelog error

CHANGELOG.md, README.md, Sampler/Build.psd1, Sampler/Sampler.psd1, build.yaml
=> added shield, documentation, changelog entry, linux build fix

CHANGELOG.md, README.md, Sampler/Build.psd1, build.yaml
=> Fix/typo & force 

.build/tasks/Build-Module.ModuleBuilder.build.ps1, CHANGELOG.md, build.yaml
=> adding release notes to Module Manifest

.build/tasks/New-Release.GitHub.build.ps1, .build/tasks/release.module.build.ps1, .vscode/settings.json, CHANGELOG.md, Sampler/Assets/CHANGELOG.md.template, Sampler/Assets/build.yaml, Sampler/PlasterTemplate/plasterManifest.xml, tests/QA/module.tests.ps1, tests/Unit/PlasterTemplate/PlasterTemplate.tests.ps1
=> fixed git test, rm tk yaml, rm default Copy DSCR

.build/tasks/release.module.build.ps1, CHANGELOG.md, build.yaml
=> Buildfromnew

.build/tasks/New-Release.GitHub.build.ps1, CHANGELOG.md
=> fixing release notes

.build/tasks/release.module.build.ps1, CHANGELOG.md
=> updating find module with module Spec

.build/tasks/Build-Module.ModuleBuilder.build.ps1, CHANGELOG.md, Sampler/Templates/Sampler/plasterManifest.xml
=> Fix sourcepath

.build/tasks/Build-Module.ModuleBuilder.build.ps1, .build/tasks/DscResource.Test.build.ps1, .build/tasks/Invoke-Pester.pester.build.ps1, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, CHANGELOG.md, README.md, RequiredModules.psd1, Resolve-Dependency.ps1, Sampler/Assets/RequiredModules.psd1, Sampler/Assets/build.yaml, Sampler/Assets/module.template, Sampler/Classes/1.class1.ps1, Sampler/Classes/2.class2.ps1, Sampler/Classes/3.class11.ps1, Sampler/Classes/4.class12.ps1, Sampler/Private/Get-PrivateFunction.ps1, Sampler/Public/Get-Something.ps1, Sampler/Sampler.psm1, Sampler/Templates/Sampler/plasterManifest.xml, azure-pipelines.yml, build.ps1, build.yaml, tests/QA/module.tests.ps1, tests/Unit/DSCResources/DSC_Folder.Tests.ps1, tests/Unit/Modules/Folder.Common.Tests.ps1, tests/Unit/PlasterTemplate/PlasterTemplate.tests.ps1
=> fixing guidline style & improving from feedback

.vscode/tasks.json, CHANGELOG.md, Sampler/Assets/gitattributes, Sampler/Assets/gitignore, Sampler/Assets/vscode/analyzersettings.psd1, Sampler/Assets/vscode/settings.json, Sampler/Assets/vscode/tasks.json, Sampler/Templates/Sampler/plasterManifest.xml
removed run task when folder opens
updated gitignore template
added vscode files to vscode folder template assets
adding attributes found in other repos
updating tasks to most useful default
adding gitignore entry as per other repos
updating template manifest with dsccommunity conversion bundle …
updating changelog
=> Added DSC Community Template type for converting DSC module repo

CHANGELOG.md, Sampler/Templates/Sampler/plasterManifest.xml
Removes the QA tests from dsc community template since ChangeLog test is implemented in DscResource.Test
To be merged after dsccommunit\DscResource.Test#51
=> removing QA test file for DSC Community template

CHANGELOG.md, azure-pipelines.yml
- Clean up of `azure-pipelines` to improve readability and output test run title.
- Set `testRunTitle` for PublishTestResults steps in `azure-pipelines.yml`
so that a helpful name is displayed in Azure DevOps for each test run.
- Removed unnecessary comments from `azure-pipelines.yml`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/91)
=> Change azure-pipelines.yml to add testRunTitle

CHANGELOG.md, azure-pipelines.yml
- Set a display name on all the jobs and tasks in the CI pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/96)
=> Set display names in the CI pipeline

CHANGELOG.md, azure-pipelines.yml
- Fix casing in key names in `azure-pipelines.yml`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/98)
=> Fix casing in key names in azure-pipelines.yml

CHANGELOG.md, azure-pipelines.yml
- Fixes #76
- Azure Pipelines will no longer trigger on changes to just the CHANGELOG.md (when merging to master).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/104)
=> Azure Pipelines will no longer trigger on CHANGELOG.md

CHANGELOG.md, Sampler/Assets/vscode/settings.json
This PR updates the Visual Studio Code `settings.json` template file with the following settings:
- "powershell.codeFormatting.pipelineIndentationStyle": "IncreaseIndentationAfterEveryPipeline"
- VSCode setting pipelineIndentationStyle.
=> Update VSCode settings.json Template File

.vscode/settings.json, CHANGELOG.md, Sampler/Assets/vscode/settings.json, azure-pipelines.yml
- Changed the VS Code project settings to trim trailing whitespace for
markdown files too.
- The deploy step is no longer run if the Azure DevOps organization URL
does not contain 'synedgy'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/109)
=> Fix VS Code settings and deploy step not running on forks

CHANGELOG.md, Sampler/Templates/Sampler/plasterManifest.xml
- Update the plaster template to replace 'synedgy' with 'dsccommunity' if
the module type is 'dsccommunity' (fixes #110).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/112)
=> Update the plaster template to replace 'synedgy'

.build/tasks/Common.Functions.ps1, .build/tasks/Invoke-Pester.pester.build.ps1, CHANGELOG.md, build.ps1
Updated the PesterScript parameter to allow the specification of hastables, to enable specifying parameters to Pester.
E.g.: 
```PowerShell
$path16 = '$path16 = "C:\src\SharePointDsc\Tests\Unit\Stubs\SharePoint\16.0.4456.1000\Microsoft.SharePoint.PowerShell.psm1"'
.\build.ps1 -Tasks test -PesterScript @{ Path =  'C:\src\SharePointDsc\tests\Unit'; Parameters = @{SharePointCmdletModule = $path16 } }
```
- Updated the PesterScript parameter to allow the specification of hastables,
to enable specifying parameters to Pester.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/117)
=> Updated PesterScript to accept hashtables

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/126)
=> Updating ChangeLog since release of v0.101.0

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/129)
=> Updating ChangeLog since release of v0.102.0

.build/tasks/Build-Module.ModuleBuilder.build.ps1, .build/tasks/Common.Functions.psm1, .build/tasks/DscResource.Test.build.ps1, .build/tasks/Invoke-Pester.pester.build.ps1, .build/tasks/Merge-CodeCoverageFiles.pester.build.ps1, .build/tasks/New-Release.GitHub.build.ps1, .build/tasks/release.module.build.ps1, CHANGELOG.md
- Changed build tasks to use the helper function `Get-ModuleVersion` to
reduce code duplication.
- [x ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/132)
=> Changed build tasks to use function Get-ModuleVersion

.build/tasks/Build-Module.ModuleBuilder.build.ps1, .build/tasks/Common.Functions.psm1, .build/tasks/DscResource.Test.build.ps1, .build/tasks/Invoke-Pester.pester.build.ps1, .build/tasks/Merge-CodeCoverageFiles.pester.build.ps1, .build/tasks/New-Release.GitHub.build.ps1, .build/tasks/release.module.build.ps1, CHANGELOG.md, Sampler/Assets/azure-pipelines.simple.yml, azure-pipelines.yml
- Changed each build task so that the default value of the parameter
`ModuleVersion` always returns the sematic version (x.y.z-prerelease),
and not the informational version (issue #130).
Fixes #130
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/131)
=> Default value of the parameter ModuleVersion always returns x.y.z-prerelease

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/139)
=> Updating ChangeLog since release of v0.102.1

.build/tasks/release.module.build.ps1, CHANGELOG.md, azure-pipelines.yml
- Now the module manifest release notes is only updated with the latest release.
This fixes the issue with the limitation for the release notes in the module
manifest when releasing a module to PowerShell Gallery. If all the change log
entries for the latest release still exceed the max hard limit then the release
notes will be truncated to the max hard limit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/143)
=> Fixes so that it used the latest release's change log in module manifest

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/144)
=> Updating ChangeLog since release of v0.103.0

.build/tasks/release.module.build.ps1, CHANGELOG.md
- It no longer updates the module manifest release notes in the task
`publish_module_to_gallery`, because that is already done in the task
`create_changelog_release_output` that is run in the build step. The
task `publish_module_to_gallery` was still dependent on the task
`create_changelog_release_output` was run for it to be able to update
the release notes in the module manifest, so `publish_module_to_gallery`
could never have been run independent of task `create_changelog_release_output`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/146)
=> Remove updating module manifest release notes in task publish_module_to_gallery

.build/tasks/release.module.build.ps1, CHANGELOG.md
- Correctly evaluate the module version in task `publish_module_to_gallery`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/148)
=> Fix module version check

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/150)
=> Updating ChangeLog since release of v0.104.0

CHANGELOG.md, Sampler/Assets/build.yaml.template
- Add new build task `Generate_Wiki_Content` for the DSC Community module type.
Fixes #142 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/149)
=> Add new build task Generate_Wiki_Content

.build/tasks/Build-Module.ModuleBuilder.build.ps1, .build/tasks/Common.Functions.psm1, CHANGELOG.md, RequiredModules.psd1, Sampler/Modules/HelperSubmodule/HelperSubmodule.psd1
- Update the repository to always use the latest version of the module
`ModuleBuilder`.
- Now the prerelease is cleaned so that it does not contain any dashes by
removing any suffix after a dash, for example `pr054-0012' will be changed
to just `pr054' as the prerelease string. This is due to a bug in the
cmdlet `Publish-Module` together with a newer version of the module
`ModuleBuilder`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/151)
=> Fix issue with using Publish-Module together with latest ModuleBuilder

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/152)
=> Updating ChangeLog since release of v0.105.0

.build/tasks/Build-Module.ModuleBuilder.build.ps1, .build/tasks/Common.Functions.psm1, .build/tasks/DscResource.Test.build.ps1, .build/tasks/Invoke-Pester.pester.build.ps1, .build/tasks/New-Release.GitHub.build.ps1, .build/tasks/release.module.build.ps1, CHANGELOG.md
I have tested this with and without GitVersion installed. Task `build` and `test` works as expected.
- Fixes #153
- The task build will no longer fail if GitVersion is not installed and
there are no output folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/154)
=> Fix build task to not fail when gitversion is missing

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/158)
=> Updating ChangeLog since release of v0.105.1

CHANGELOG.md, README.md
This is meant to help contributors how build external build tasks in other modules. This describes the possible build task variables that can be used in those build tasks.
- Updated README.md with a section Task Variables
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/138)
=> Updated README.md with a section Task Variables

.build/tasks/Build-Module.ModuleBuilder.build.ps1, .build/tasks/Common.Functions.psm1, .build/tasks/DeployAll.PSDeploy.build.ps1, .build/tasks/DscResource.Test.build.ps1, .build/tasks/Invoke-Pester.pester.build.ps1, .build/tasks/Merge-CodeCoverageFiles.pester.build.ps1, .build/tasks/New-Release.GitHub.build.ps1, .build/tasks/generateHelp.PlatyPS.build.ps1, .build/tasks/release.module.build.ps1, CHANGELOG.md, build.yaml
- Fixes #125 
- Fixes #155 
- When there are multiple module manifest found in the repository the build
now fails with a a better error error message ([issue #155](https://github.com/gaelcolas/Sampler/issues/155)).
- Update tasks to reduce code duplication ([issue #125](https://github.com/gaelcolas/Sampler/issues/125)).
- Task 'Merge_CodeCoverage_Files' did not use the parameter `ProjectName`
to that parameter was removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/156)
=> Update tasks to reduce code duplication

.build/tasks/Build-Module.ModuleBuilder.build.ps1, .build/tasks/Common.Functions.psm1, .build/tasks/DscResource.Test.build.ps1, .build/tasks/Invoke-Pester.pester.build.ps1, .build/tasks/New-Release.GitHub.build.ps1, .build/tasks/release.module.build.ps1, CHANGELOG.md
- Fixes #160
- Tasks that are not setting the version in the module manifest or otherwise
need to evaluate the module version are now using the the module version
from the nodule manifest that the build task evaluated and set (issue #160).
- Fixed so module version can be detected using GitVersion on macOS and
Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/162)
=> Some tasks are now only using module manifest version number

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/164)
=> Updating ChangeLog since release of v0.105.2

.build/tasks/Build-Module.ModuleBuilder.build.ps1, CHANGELOG.md
- Removed not needed attempt to use ModuleBuilder's build manifest (build.psd1)
from the build task. It was trying to determine the source path by using
the `SourcePath` property from the build manifest. But since the build
manifest is in the source path the source path must already be known
to be able to import the build manifest. Catch 22. The code also wrongly
assumed that the `SourcePath` needed to include the module manifest file
which it should not since that is determined by ModuleBuilder using
the source path as base path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/167)
=> Removed not needed attempt to use ModuleBuilder's build manifest

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/168)
=> Updating ChangeLog since release of v0.105.3

.build/tasks/DscResource.Test.build.ps1, .build/tasks/Invoke-Pester.pester.build.ps1, CHANGELOG.md, RequiredModules.psd1, build.yaml
- Added Pester 5 support in the CI pipeline test task.
- Pinned the module Pester to v4.10.1 in the file `RequiredModule.psd1`
until this repo is converted to Pester 5.
The file `build.yaml` must be updated in repos that should run Pester 5. Minimum is to replace `Script` with `Path`.
```
Pester:
Path:
- tests/QA
- tests/Unit
- tests/Integration
ExcludeTag:
Tag:
Output: Detailed
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/173)
=> Update CI test task to support Pester 5

.build/tasks/Build-Module.ModuleBuilder.build.ps1, CHANGELOG.md, Sampler/Assets/build.psd1.template, Sampler/Assets/build.yaml.template, Sampler/Build.psd1, Sampler/Templates/Sampler/plasterManifest.xml, build.yaml
- Update build task to pass the full path to the module manifest to
`Build-Module` to be able to build without a build manifest.
- Remove the build manifest.
- Change the build.yaml to use `CopyPaths` instead of `CopyDirectories`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/171)
=> Able to build without a build manifest

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/174)
=> Updating ChangeLog since release of v0.105.4

.build/tasks/Invoke-Pester.pester.build.ps1, CHANGELOG.md
- Fix for Pester 5.0.1 making sure only to use the `Simple` ParameterSet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/175)
=> Fixes Pester task to use the Simple ParameterSet

.build/tasks/DscResource.Test.build.ps1, .build/tasks/generateHelp.PlatyPS.build.ps1, CHANGELOG.md
This PR corrects the DscResource.Test task.
@johlju - can you review this one?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/176)
=> Fix DscResource.Test Task

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/177)
=> Updating ChangeLog since release of v0.105.5

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/179)
=> Updating ChangeLog since release of v0.105.6

CHANGELOG.md, tests/Integration/CompleteModuleNoBuildPlasterTemplate.Integration.Tests.ps1, tests/Integration/CompleteModulePlasterTemplate.Integration.Tests.ps1, tests/Integration/CustomModulePlasterTemplate.Integration.Tests.ps1, tests/Integration/DscCommunityPlasterTemplate.Integration.Tests.ps1, tests/Integration/IntegrationTestHelpers.psm1, tests/Integration/SimpleModuleNoBuildPlasterTemplate.Integration.Tests.ps1, tests/Integration/SimpleModulePlasterTemplate.Integration.Tests.ps1
- Added integration tests for the Plaster templates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/180)
=> Fix integration tests for the Plaster templates

.build/tasks/Clean.ModuleBuilder.build.ps1, .build/tasks/DeployAll.PSDeploy.build.ps1, .build/tasks/GitHubRelease.functions.ps1, .build/tasks/Merge-CodeCoverageFiles.pester.build.ps1, .build/tasks/New-Release.GitHub.build.ps1, .build/tasks/Set-BuildEnvironment.BuildHelpers.build.ps1, .build/tasks/release.module.build.ps1, CHANGELOG.md
This PR adds some additional logging to New-Release.GitHub.build.ps1
Also corrected a couple of style inconsistencies and removed some markdown linting failures in CHANGELOG.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/188)
=> Added additional logging to New-Release.GitHub.build.ps1

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/189)
=> Updating ChangeLog since release of v0.106.0

.build/tasks/New-Release.GitHub.build.ps1, CHANGELOG.md
Fixed `New-Release.GitHub.build.ps1` task `Create_ChangeLog_GitHub_PR` so that it respects `MainGitBranch` if passed.
Fixed `New-Release.GitHub.build.ps1` task `Create_ChangeLog_GitHub_PR` so that it respects `MainGitBranch` if passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/190)
=> Fix Create_ChangeLog_GitHub_PR to support main branch

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/191)
=> Updating ChangeLog since release of v0.106.1

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/195)
=> Updating ChangeLog since release of v0.107.0

.build/tasks/Build-Module.ModuleBuilder.build.ps1, CHANGELOG.md
fix #192
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/196)
=> fixing build error in Windows PS when moduleInfo is rooted path

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/197)
=> Updating ChangeLog since release of v0.107.1

.build/tasks/release.module.build.ps1, CHANGELOG.md, Sampler/Templates/Build/build.yaml.template
as per #197 I introduced a build error for the Update Changelog PRs.
This is a fix, and I updated the template to add `DscResources` folder to `copyPaths:` in Build.yml for projects that includes DSC Resources (MOF).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/199)
=> fixing Changelog PR error and CopyPaths: DSC Resource

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/200)
=> Updating ChangeLog since release of v0.107.2

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/202)
=> Updating ChangeLog since release of v0.107.3

CHANGELOG.md, README.md, Sampler/Templates/PublicFunction/Get-Something.ps1.template, Sampler/Templates/Sampler/Get-Something.ps1, Sampler/Templates/Sampler/plasterManifest.xml, tests/Integration/PlasterTemplates/Sampler/CustomModulePlasterTemplate.Integration.Tests.ps1, tests/Integration/PlasterTemplates/Sampler/SimpleModuleNoBuildPlasterTemplate.Integration.Tests.ps1, tests/Integration/PlasterTemplates/Sampler/SimpleModulePlasterTemplate.Integration.Tests.ps1
Simplifying the template and updating the readme with video.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/203)
=> Updating template & readme

CHANGELOG.md, LICENSE, RequiredModules.psd1, Resolve-Dependency.ps1, Sampler/Public/Add-Sample.ps1, Sampler/Public/New-SampleModule.ps1, Sampler/Sampler.psd1, Sampler/Sampler.psm1, Sampler/Templates/Build/RequiredModules.psd1, Sampler/Templates/Build/RequiredModules.psd1.template, Sampler/Templates/Build/Resolve-Dependency.ps1, Sampler/Templates/Build/Resolve-Dependency.psd1.template, Sampler/Templates/Build/build.ps1, Sampler/Templates/Sampler/plasterManifest.xml, Sampler/suffix.ps1, build.ps1
- Updated code style to match the DSC Community style guideline.
- Updated logic that handles the installation on PSDepend in the bootstrap
file `Resolve-Dependency.ps1`.
- Updated year in LICENSE.
- Fixed missing 'PSGallery' in build files when the Plaster parameter
`CustomRepo` is not assigned a value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/204)
=> Fix style and bugs

CHANGELOG.md, Sampler/Templates/Build/Resolve-Dependency.psd1.template, Sampler/Templates/Build/build.yaml.template, Sampler/Templates/Git/GitVersion.yml, Sampler/Templates/GithubConfig/ISSUE_TEMPLATE/Problem_with_resource.md.template, Sampler/Templates/GithubConfig/PULL_REQUEST_TEMPLATE_dsccommunity.md, Sampler/Templates/GithubConfig/plasterManifest.xml, Sampler/Templates/Sampler/CHANGELOG.md.template, Sampler/Templates/Sampler/azure-pipelines_dsccommunity.yml, Sampler/Templates/Sampler/codecov_dsccommunity.yml, Sampler/Templates/Sampler/plasterManifest.xml, tests/Integration/PlasterTemplates/Sampler/DscCommunityPlasterTemplate.Integration.Tests.ps1
This updates the Plaster template module type 'dsccommunity' to use the latest pipeline files. The correct azure-pipelines.yml and Codecov.io support. It also makes a build.yml cleaner when using that module type. 
- Added a new template file for azure-pipelines.yml when using the
module type `'dsccommunity'`.
- Added a new template and configuration for Codecov.io when using
module type `'dsccommuntity'`.
- Updated the template GitVersion.yml to use specific words to bump
major version (previously it bumped if the word was found anywhere in
the commit message even if it was part of for example a code variable).
- Updated the template file build.yaml to make it more clean when using
the module type `'dsccommunity'`.
- Fixed a whitespace issue in the template file Resolve-Dependency.psd1. …
=> Fix DSC Community Plaster template

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/207)
=> Updating ChangeLog since release of v0.108.0

CHANGELOG.md, Sampler/Templates/Sampler/plasterManifest.xml
Updating plastermanifest.xml in sampler template : 
* [fix #67] : Replace "FunctionsToExport = '*'" by "FunctionsToExport = ''"
* [fix #69] : Add "Prerelease = ''" in "PSData" block 
- Update plasterManifest.xml call by New-SampleModule :
- Add section modify to replace "FunctionsToExport = '*'" by "FunctionsToExport = ''" in new module manifest ([issue #67](https://github.com/gaelcolas/Sampler/issues/67)).
- Add section modify to add "Prerelease = ''" in "PSData" block  in new module manifest ([issue #69](https://github.com/gaelcolas/Sampler/issues/69)). 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/210)
=> Updating plasterManifest to resolve issues #67 and #69

CHANGELOG.md, Sampler/Templates/Sampler/azure-pipelines.simple.yml, Sampler/Templates/Sampler/azure-pipelines.yml, Sampler/Templates/Sampler/azure-pipelines_dsccommunity.yml, azure-pipelines.yml
- [fix: #159] - Updating all azure-pipeline.yaml to change Build Artifacts to Pipeline Artifacts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/211)
=> Updating all azure-pipeline.yaml to change Build  to Pipeline Artifacts

.build/tasks/Build-Module.ModuleBuilder.build.ps1, .build/tasks/Common.Functions.psm1, CHANGELOG.md
Added new task Build_DscResourcesToExport_ModuleBuilder.
The new task Build_DscResourcesToExport_ModuleBuilder add DsResources name in DscResourcesToExport manifest key.
- Added new function Get-ClassBasedResourceName on Common.Functions.psm1 module.
It's used to find the class-based resource defined in psm1 file.
- Added new task Build_DscResourcesToExport_ModuleBuilder.
On build, it adds DscResources (class or Mof) in DscResourcesToExport manifest key.
- Renamed Build_Module_ModuleBuilder task to Build_ModuleOutPut_ModuleBuilder.
Build_Module_ModuleBuilder is now a metatask that calls
Build_ModuleOutPut_ModuleBuilder and Build_DscResourcesToExport_ModuleBuilder tasks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Add task Build_DscResourcesToExport_ModuleBuilder

.build/tasks/Build-Module.ModuleBuilder.build.ps1, .build/tasks/Common.Functions.psm1, .build/tasks/release.module.build.ps1, CHANGELOG.md
- Fixed Test-ModuleManifest in tasks. [fix #208]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/215)
=> Fixed Test-ModuleManifest #208

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/216)
=> Updating ChangeLog since release of v0.109.0

.build/tasks/Build-Module.ModuleBuilder.build.ps1, .build/tasks/Common.Functions.psm1, CHANGELOG.md
The task searchs the schema.mof file in DSCResource folder and search the friendlyName in MOF File with regex. 
If no friendlyname found, the task uses the BaseName of DSCResource Folder. 
- Wrong resource name is added to module manifest property DscResourcesToExport #220
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/221)
=> Fix wrong resource name is added in manifest #220

CHANGELOG.md, README.md
I fixed a few typos.  
Note, it would be nice to add a mention to the [Sampler](https://www.powershellgallery.com/packages/Sampler) module on this page as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/224)
=> Fix typos in the README.md

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/228)
=> Updating ChangeLog since release of v0.109.1

.build/tasks/release.module.build.ps1, CHANGELOG.md, build.yaml
- The Deploy tasks `publish_nupkg_to_gallery` and `publish_module_to_gallery`
are now made mutually exclusive. For each deploy pipeline you must choose
to use either one. 
- `publish_nupkg_to_gallery` is using `nuget` to publish to the gallery.
- `publish_module_to_gallery` is using the cmdlet `Publish-Module` to
publish to the gallery.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/217)
=> Make deploy tasks mutually exclusive

.build/tasks/Build-Module.ModuleBuilder.build.ps1, .build/tasks/release.module.build.ps1, CHANGELOG.md, build.yaml
- Fixes #230 - Fix issue in DscResourcesToExport task to properly process DscResource schema
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/231)
=> Fixes issue #230

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/232)
=> Updating ChangeLog since release of v0.109.2

CHANGELOG.md, Sampler/Templates/Sampler/azure-pipelines_dsccommunity.yml
- Fix uploading of code coverage when using the DSC Community template.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/234)
=> Fix uploading of code coverage when using the DSC Community template

.build/tasks/Invoke-Pester.pester.build.ps1, CHANGELOG.md, Sampler/Templates/Build/build.ps1, build.ps1
- Fixed bug when using `PesterScript` with the build task `Invoke_Pester_Tests`
when running Pester 5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/233)
=> Fixed bug in build task Invoke_Pester_Tests

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/236)
=> Updating ChangeLog since release of v0.109.3

CHANGELOG.md, Sampler/Templates/Build/build.yaml.template, build.yaml
fixing workflow to create changelog PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/242)
=> fixing workflow to create changelog PR

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/244)
=> Updating ChangeLog since release of v0.109.5

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/251)
=> Updating ChangeLog since release of v0.109.6

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/253)
=> Updating ChangeLog since release of v0.109.7

.build/tasks/Build-Module.ModuleBuilder.build.ps1, CHANGELOG.md
- Fix issue when there is no root module.
- Fix to use correct path when determine class-based resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/254)
=> Fix issue when there is no root module

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/255)
=> Updating ChangeLog since release of v0.109.8

.build/tasks/Build-Module.ModuleBuilder.build.ps1, CHANGELOG.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/256)
=> Fix to correctly evalute path

.build/tasks/Build-Module.ModuleBuilder.build.ps1, CHANGELOG.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/257)
=> Fix changelog

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/258)
=> Updating ChangeLog since release of v0.109.9

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/262)
=> Updating ChangeLog since release of v0.109.10

.build/tasks/Invoke-Pester.pester.build.ps1, CHANGELOG.md, Sampler/Public/Merge-JaCoCoReport.ps1, Sampler/Public/Update-JaCoCoStatistic.ps1, azure-pipelines.yml, build.yaml, codecov.yml, tests/Unit/Public/Update-JaCoCoStatistic.tests.ps1
- Support for code coverage when using ModuleBuilder pattern for building module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/263)
=> Add ModuleBuilder pattern code coverage support

CHANGELOG.md, azure-pipelines.yml, codecov.yml
- Fixed codecov.yml to parse version number in paths correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/265)
=> Fix codecov.yml to parse version number correctly

CHANGELOG.md, Resolve-Dependency.ps1
Found two issues when running `Resolve-Dependency.ps1`.
```powershell
PS C:\> C:\dev\SocketHttpRequest\Resolve-Dependency.ps1
Save-Module : Cannot find the path 'C:\dev\SocketHttpRequest\.\output\RequiredModules' because it does not exist.
At C:\dev\SocketHttpRequest\Resolve-Dependency.ps1:340 char:13
+             Save-Module @saveModuleParameters
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Save-Module], InvalidOperationException
+ FullyQualifiedErrorId : PathNotFound,Save-Module
```
```powershell
PS C:\> C:\dev\SocketHttpRequest\Resolve-Dependency.ps1
Save-Module : Cannot find the path 'C:\dev\SocketHttpRequest\output\RequiredModules' because it does not exist.
At C:\dev\SocketHttpRequest\Resolve-Dependency.ps1:340 char:13
+ …
```
=> [Resolve-Dependency.ps1] Fix/PSDependTarget param & force save-module

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/268)
=> Updating ChangeLog since release of v0.110.0

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/270)
=> Updating ChangeLog since release of v0.110.1

.build/tasks/Build-Module.ModuleBuilder.build.ps1, CHANGELOG.md, README.md, Sampler/Templates/Build/build.yaml.template
- It is not possible to specify module semantic version in the build.yml
using the key `SemVer`, e.g. `SemVer: '99.0.0-preview1'`. This can be
used if the preferred method of using GitVersion is not available.
- Fixes #279 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/282)
=> Fix to use SemVer in build.yml

CHANGELOG.md, GitVersion.yml, Sampler/Sampler.psd1, azure-pipelines.yml, build.yaml, codecov.yml, tests/QA/module.tests.ps1
- Renamed default branch to `main`.
Fixes #235 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/281)
=> Update pipeline files to support change of default branch to main

.build/tasks/Invoke-Pester.pester.build.ps1, CHANGELOG.md
This PR continues the work of @NicolasBn. 
- Fixes #223
- Added new build task `Import_Pester` ([issue #223](https://github.com/gaelcolas/Sampler/issues/223)).
- Added new build task `Invoke_Pester_Tests_v5` ([issue #223](https://github.com/gaelcolas/Sampler/issues/223)).
- Task `Invoke_Pester_Tests_v5` will not run if Pester 4 is used in the pipeline.
- Task `Invoke_Pester_Test` was renamed to `Invoke_Pester_Tests_v4`.
- Pester 5 support was removed from the task and replaced with `Invoke_Pester_Tests_v5`
- Task `Invoke_Pester_Tests_v4` will not run if Pester 5 is used in the pipeline.
- Meta build task `Pester_Tests_Stop_On_Fail` was change to run `Import_Pester`,
`Invoke_Pester_Tests_v4` (previously `Invoke_Pester_Test`), and `Invoke_Pester_Tests_v5`.
- Task `Invoke_Pester_Tests_v4` …
=> Support Pester 5 coverage and more options for test pipeline

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/287)
=> Updating ChangeLog since release of v0.111.0

.build/tasks/Invoke-Pester.pester.build.ps1, CHANGELOG.md
- Task `Invoke_Pester_Tests_v5`
- Now the Pester advanced configuration correctly handles `false` values
in the build configuration files.
- Now the Pester object, that is written to file by to the pipeline,
correctly holds all expected objects. `Export-CliXml` defaulted to two
levels of depth, now it exports five levels.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/288)
=> Resolve bugs in task `Invoke_Pester_Tests_v5`

.build/tasks/Invoke-Pester.pester.build.ps1, CHANGELOG.md
- Now the task `Pester_If_Code_Coverage_Under_Threshold` report the code coverage
and correctly fail if the code coverage is under the code coverage threshold.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/289)
=> Fix task Pester_If_Code_Coverage_Under_Threshold to handle Pester 5

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/290)
=> Updating ChangeLog since release of v0.111.1

.build/tasks/Invoke-Pester.pester.build.ps1, CHANGELOG.md
- Now the task `Pester_If_Code_Coverage_Under_Threshold` correctly honors
the zero value (`0`) of the parameter `CodeCoverageThreshold` when using
`build.ps1`, and honors the zero value (`0`) of the Pester advanced build
configuration key `CoveragePercentTarget`. If the value is set to `0` the
task will now be skipped since code coverage was disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/293)
=> Fix task `Pester_If_Code_Coverage_Under_Threshold`

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/294)
=> Updating ChangeLog since release of v0.111.2

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/296)
=> Updating ChangeLog since release of v0.111.3

.build/tasks/Invoke-Pester.pester.build.ps1, CHANGELOG.md
- Task `Invoke_Pester_Tests_v4`
- It now once again works using a hashtable together with parameter
`PesterScript` ([issue #303](https://github.com/gaelcolas/Sampler/issues/303)).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/304)
=> `Invoke_Pester_Tests_v4`: Fix using hashtable with PesterScript

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/305)
=> Updating ChangeLog since release of v0.111.4

.build/tasks/Invoke-Pester.pester.build.ps1, .build/tasks/JaCoCo.coverage.build.ps1, CHANGELOG.md
- The task `Invoke_Pester_Tests_v5` no longer fails when using Pester 
v5.3.0-alpha5 (issue #307).
- The task `Convert_Pester_Coverage` no longer fails when using a preview
version of Pester (issue #301).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/308)
=> Fix Pester 5 bugs

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/309)
=> Updating ChangeLog since release of v0.111.5

CHANGELOG.md
My Last PR didn't correctly format the changelog.MD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/311)
=> Fix CHANGELOG.MD

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/314)
=> Updating ChangeLog since release of v0.111.6

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/318)
=> Updating ChangeLog since release of v0.111.8

.build/tasks/release.module.build.ps1, CHANGELOG.md
Added ability to pass in WhatIf parameter to release.module.build.ps1. This enables users to run Publish-Module with a -WhatIf parameter.
- Added -WhatIf parameter to `release.module.build.ps1`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/320)
=> Add WhatIf feature

CHANGELOG.md, README.md
- Updated Sampler documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/321)
=> Update Sampler documentation

CHANGELOG.md, Sampler/Templates/Sampler/azure-pipelines.yml.template, Sampler/Templates/Sampler/azure-pipelines_dsccommunity.yml.template, azure-pipelines.yml
- Fix azure-pipelines.yml where variables are not possible to use.
- [ x Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/323)
=> Fix azure-pipelines.yml

CHANGELOG.md, Sampler/Templates/Sampler/azure-pipelines.yml.template, Sampler/Templates/Sampler/azure-pipelines_dsccommunity.yml.template, azure-pipelines.yml
- Fix azure-pipelines.yml where variables are not possible to use (triggers
and deploy condition).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/324)
=> Fix deploy pipeline

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/330)
=> Updating ChangeLog since release of v0.112.0

CHANGELOG.md, CONTRIBUTING.md, Sampler/Templates/Build/CONTRIBUTING.md
- Fixed missing full stop (`.`) in the CONTRIBUTING.md. Fixes [#333](https://github.com/gaelcolas/Sampler/issues/333).
Fixes #333 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/343)
=> Fix missing full stop (`.`) in the CONTRIBUTING.md

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/344)
=> Updating ChangeLog since release of v0.112.1

CHANGELOG.md, Sampler/Templates/Sampler/azure-pipelines.yml.template, Sampler/Templates/Sampler/azure-pipelines_dsccommunity.yml.template, azure-pipelines.yml
- Switch to installing GitVersion using `dotnet tool install`. Fixes [#348](https://github.com/gaelcolas/Sampler/issues/348)
- Updated pipeline to use the build worker image 'ubuntu-latest'.
- Updated pipeline to use the build worker image 'windows-latest'.
- Updated the Plaster templates
- to use 'dotnet tool install' in the pipeline.
- to use build image 'ubuntu-latest' in the pipeline.
- to use build image 'windows-latest' in the pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/349)
=> Switch to installing GitVersion using dotnet tool install

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/354)
=> Updating ChangeLog since release of v0.112.2

.build/tasks/release.module.build.ps1, CHANGELOG.md, Sampler/Public/Get-BuildVersion.ps1, Sampler/scripts/Set-SamplerTaskVariable.ps1, tests/Unit/Public/Get-BuildVersion.tests.ps1
- Now the module manifest is again updated with the release notes (from
the changelog). Fixes [#358](https://github.com/gaelcolas/Sampler/issues/358)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/364)
=> Update release notes in module manifest

CHANGELOG.md, Sampler/suffix.ps1
- Fixed a problem which occurred on certain machined when using Sampler in
Windows PowerShell. Fixes [#350](https://github.com/gaelcolas/Sampler/issues/350)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/369)
=> Fix issue using Sampler with Windows PowerShell

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/370)
=> Updating ChangeLog since release of v0.114.0

CHANGELOG.md, Sampler/Public/Get-BuildVersion.ps1
- Now supports getting module version from `dotnet-gitversion` if it is available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/372)
=> Get module version from `dotnet-gitversion`

CHANGELOG.md, Resolve-Dependency.ps1, Resolve-Dependency.psd1, Sampler/Templates/Build/Resolve-Dependency.ps1, Sampler/Templates/Build/Resolve-Dependency.psd1.template
- Supports using a private Nuget repository, e.g. a _Azure DevOps Server_
_Pipelines_ feed that is using Windows integrated security, or a feed with
no security.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/371)
=> Add support for private Nuget feed (with limitations)

CHANGELOG.md, tests/QA/module.tests.ps1
- Fixed QA test that was breaking release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/378)
=> Fix QA test

CHANGELOG.md, Sampler/Public/Merge-JaCoCoReport.ps1, tests/Unit/Public/Merge-JaCoCoReport.tests.ps1
- `Merge-JaCoCoReport`
- Improvements to be able to merge missing elements, like entire element
`<class>`, `<sourcefile>`, `<method>`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/386)
=> Improve `Merge-JaCoCoReport`

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/401)
=> Updating ChangeLog since release of v0.116.0

.build/tasks/Build-Module.ModuleBuilder.build.ps1, .vscode/launch.json, CHANGELOG.md, Sampler/Public/Get-Psm1SchemaName.ps1, tests/Unit/Public/Get-Psm1SchemaName.tests.ps1, tests/Unit/tasks/Build-Module.ModuleBuilder.build.Tests.ps1
The task `Build_DscResourcesToExport_ModuleBuilder` did not properly look for DSC MOF-based resources and DSC composite resources. It uses `Get-ChildItem -Include '*.schema.mof' -File` which in some cases returns more than just `*.schema.mof` files.
https://github.com/gaelcolas/Sampler/blob/0df39036bac42ecdf15ed956d8bc5e3fc30995c7/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L359
Discovering the name of DSC composite resources must be done differently, hence a [Get-Psm1SchemaName.ps1](https://github.com/gaelcolas/Sampler/pull/403/files#diff-30438c5323d73886608efc20022f943222ceb74bfb9537f745046766b957a64b) was added.
The changes of this PR mainly add support for DSC composite resources.
- #402: Using parameter `Filter` instead of `Include` to get MOF files.
- Support for DSC composite …
=> MOF Files are identified incorrectly

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/409)
=> Updating ChangeLog since release of v0.116.1

CHANGELOG.md, Sampler/scripts/Set-SamplerTaskVariable.ps1
Added debug output of PSModulePath
Added debug output of PSModulePath to support new task 'Set_PSModulePath'
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/416)
=> Added debug output of PSModulePath

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/418)
=> Updating ChangeLog since release of v0.116.2

CHANGELOG.md, Sampler/Templates/Build/README.md.template, Sampler/Templates/Build/RequiredModules.psd1.template, Sampler/Templates/Build/build.yaml.template, Sampler/Templates/Sampler/about_ModuleName.help.template, Sampler/Templates/Sampler/module.template, Sampler/Templates/Sampler/module.tests.ps1.template, Sampler/Templates/Sampler/plasterManifest.xml, tests/Integration/PlasterTemplates/Sampler/CompleteSamplePlasterTemplate.Integration.Tests.ps1, tests/Integration/PlasterTemplates/Sampler/CustomModulePlasterTemplate.Integration.Tests.ps1, tests/Integration/PlasterTemplates/Sampler/DscCommunityPlasterTemplate.Integration.Tests.ps1, tests/Integration/PlasterTemplates/Sampler/SimpleModuleNoBuildPlasterTemplate.Integration.Tests.ps1, tests/Integration/PlasterTemplates/Sampler/SimpleModulePlasterTemplate.Integration.Tests.ps1
- Template `SimpleModule`
- The template has been changed to create a module with the minimum scaffolding
when using default values for the template questions. The minimum scaffolding
enable the building and testing of the module, but default there is no pipeline
so it possible to use any platform to run the pipeline.
- Additional template parameters have been added which will add additional
functionality to the module.
- `UseGit` - This parameter enables project files that helps with the use
of Git for the project. The template will ask if Git should be used, default
is No.
- `UseGitVersion` - This parameter adds project files that helps with
the use of GitVersion for the project. GitVersion is dependent on Git
being used for the project. The template will ask if GitVersion should
be …
=> Make template SimpleModule better

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/420)
=> Updating ChangeLog since release of v0.116.3

CHANGELOG.md, Resolve-Dependency.ps1, Sampler/Templates/Build/Resolve-Dependency.ps1
- Fix a bug that prevented downloading of dependent modules that has a
dependency on the module _PowerShell-Yaml_. Fixes [#421](https://github.com/gaelcolas/Sampler/issues/421).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/422)
=> Allows downloading of modules dependent on PowerShell-Yaml

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/423)
=> Updating ChangeLog since release of v0.116.4

CHANGELOG.md, Sampler/Templates/Sampler/azure-pipelines.yml.template, Sampler/Templates/Sampler/azure-pipelines_dsccommunity.yml.template, azure-pipelines.yml
New Azure Pipelines do shallow fetch by default which make GitVersion to fail since all commit history is not available.
- `azure-pipelines.yml`
- Fixes #424 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/425)
=> Fix shallow fetch depth in pipeline

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/427)
=> Updating ChangeLog since release of v0.116.5

CHANGELOG.md, tests/Integration/PlasterTemplates/Sampler/CompleteSamplePlasterTemplate.Integration.Tests.ps1, tests/Integration/PlasterTemplates/Sampler/CustomModulePlasterTemplate.Integration.Tests.ps1, tests/Integration/PlasterTemplates/Sampler/DscCommunityPlasterTemplate.Integration.Tests.ps1, tests/Integration/PlasterTemplates/Sampler/SimpleModuleNoBuildPlasterTemplate.Integration.Tests.ps1, tests/Integration/PlasterTemplates/Sampler/SimpleModulePlasterTemplate.Integration.Tests.ps1
- Fix unit tests that was wrongly written and failed on Pester 5.5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/435)
=> Fix unit tests that was wrongly written and failed on Pester 5.5

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/444)
=> Updating ChangeLog since release of v0.117.0

.build/tasks/release.module.build.ps1, CHANGELOG.md
- Correct description of the parameter `GalleryApiToken` in the build task
script release.module.build.ps1. Fixes [#442](https://github.com/gaelcolas/Sampler/issues/442)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/455)
=> Update GalleryApiToken description in release.module.build.ps1

CHANGELOG.md, README.md, Resolve-Dependency.ps1, Resolve-Dependency.psd1, Sampler/Templates/Build/Resolve-Dependency.ps1, Sampler/Templates/Build/Resolve-Dependency.psd1.template
- Also default to using PowerShellGet v3 which is a compatibility module that is a wrapper
for the equivalent command in PSResourceGet.
- Now PSResourceGet always default to the latest released version if no
specific version is configured or passed as parameter.
- Now it won't import legacy PowerShellGet and PackageManagement when
PSResourceGet or ModuleFast is used.
- Now it works saving PowerShellGet compatibility module when configured.
- Now if both ModuleFast and PowerShellGet compatibility module is configured
PSResourceGet is automatically added as a dependency. This is for example
needed for publishing built module to the gallery.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Update to use PowerShell compatibility module

CHANGELOG.md, README.md, Sampler/Templates/Sampler/module.tests.ps1.template
- Update template for module.tests.ps1.
- Fixes #465 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/466)
=> Update the module.tests.ps1 template

CHANGELOG.md, RequiredModules.psd1, Sampler/Templates/Build/build.yaml.template, Sampler/WikiSource/Home.md, build.yaml
- Automatic wiki documentation for public commands.
- Public command documentation has been moved from README.md to the GitHub
repository Wiki.
- Update order of deploy tasks for the Plaster templates to make it easier
to re-run a deploy phase when a GitHub token has expired.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/471)
=> Automatic wiki documentation

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/476)
=> Updating ChangeLog since release of v0.118.1

.github/ISSUE_TEMPLATE/Problem_with_module.yml, CHANGELOG.md, Sampler/Templates/GithubConfig/ISSUE_TEMPLATE/Problem_with_module.yml.template
- Fix issue template in repository and Plaster template ([issue #483](https://github.com/gaelcolas/Sampler/issues/483)).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/484)
=> Fix issue template

.build/tasks/release.module.build.ps1, CHANGELOG.md, tests/Unit/tasks/release.module.build.Tests.ps1
- Task `publish_module_to_gallery`
- Changed to use `Publish-PSResource` if available.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/506)
=> Update `publish_module_to_gallery` to use `Publish-PSResource` if available

.build/tasks/release.module.build.ps1, CHANGELOG.md
- Task `publish_module_to_gallery`
- Remove unnecessary debug information.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/507)
=> Remove debug code in `publish_module_to_gallery`

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/508)
=> Updating ChangeLog since release of v0.118.2

CHANGELOG.md, Sampler/en-US/Sampler.strings.psd1, azure-pipelines.yml, tests/Integration/SimpleModule.Integration.Tests.ps1
- Fixed issue with localization string testing with new version of the HQRM
tests (module DscResource.Test).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/514)
=> Fixed localization testing with new HQRM tests

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/522)
=> Updating ChangeLog since release of v0.118.3

CHANGELOG.md, Resolve-Dependency.ps1, Sampler/Templates/Build/Resolve-Dependency.ps1, azure-pipelines.yml
This fixes #510.
- Add retry logic for ModuleFast dependency installation (fixes #510).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/518)
=> Add retry logic for ModuleFast dependency installation (#510)

.vscode/analyzersettings.psd1, CHANGELOG.md, Resolve-Dependency.ps1, Sampler/Templates/Build/Resolve-Dependency.ps1, Sampler/Templates/Build/build.ps1, Sampler/Templates/ChocolateyPackage/myPackage/tools/chocolateyuninstall.ps1, Sampler/Templates/ClassFolderResource/tests/Unit/ClassResource/DSC_ClassFolder.tests.ps1, Sampler/Templates/Classes/tests/Unit/Classes/class1.tests.ps1, Sampler/Templates/Classes/tests/Unit/Classes/class11.tests.ps1, Sampler/Templates/Classes/tests/Unit/Classes/class12.tests.ps1, Sampler/Templates/Classes/tests/Unit/Classes/class2.tests.ps1, Sampler/Templates/MofResource/tests/Unit/Modules/Folder.Common.tests.ps1, Sampler/scripts/Set-SamplerTaskVariable.ps1, build.ps1, build.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/540)
=> Fix Script Analyzer QA tests failing in various scripts
