gaelcolas/Sampler

- .build/tasks/Invoke-Pester.pester.build.ps1
- CHANGELOG.md
- build.ps1
Now setting the CodeCoverageThreshold to `0` will bypass the codecoverage (no calculation in pester) but will still assert no tests were failing.
Also, setting CodeCoverageThreshold to 0 from parameters will not be overridden by Config File anymore.
Also checking keys before loading from config file.
> fixing codecoverage parameter handling logic

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- build.ps1
- build.yaml
As discussed, allowing DscTestTag & DscTestExcludeTag parameters to be set when invoking `build.ps1`.
> adding params to build.ps1

- CHANGELOG.md
- Sampler/Assets/RequiredModules.psd1.template
- Sampler/Assets/Resolve-Dependency.psd1.template
- Sampler/Assets/build.yaml.template
- Sampler/Templates/Sampler/plasterManifest.xml
- tests/Unit/PlasterTemplate/PlasterTemplate.tests.ps1
- build.yaml, RequiredModules.psd1 and Resolve-Dependency.psd1 are now templated
assets with conditional content.
- HQRM tests to run only when using the dsccommunity module type.
- Updated simple module to not contain sample scripts & tests.
- supports setting CustomRepo to pull dependencies from a private gallery
other than PSGallery.
> making a simplemodule template

- .build/tasks/Build-Module.ModuleBuilder.build.ps1
- .build/tasks/DeployAll.PSDeploy.build.ps1
- .build/tasks/DscResource.Test.build.ps1
- .build/tasks/Invoke-Pester.pester.build.ps1
- .build/tasks/New-Release.GitHub.build.ps1
- .build/tasks/generateHelp.PlatyPS.build.ps1
- .build/tasks/release.module.build.ps1
- CHANGELOG.md
This PR contains changes to all build task so that the user receives an appropriate error (warning) message, when the build tasks couldn't be loaded because calls to `Test-ModuleManifest`  are failing.
**Background:** I spend almost 4 hours of debugging why a module cant' be built with the Sampler infrastructure, because the error message `ERROR: Missing property 'Projectname'` constantly popped up.
Finally I discovered that I missed to add a couple of dependent modules to `RequiredModules.psd1` which let the  `Test-ModuleManifest` constantly fail on the module's `*.psd1` file, which will ultimately fail to evaluate the expression for the `ProjectName` property in the build tasks `param` specification. 
```Powershell
[Parameter()]
[string]
$ProjectName = (property ProjectName $(
#Find the …
```
> Added warning messages to build tasks, while resolving project properties

- CHANGELOG.md
- build.ps1
- `build.ps1` will now dynamically determine the build configuration if not specified via the `-BuildConfig` parameter
> Enhancement: Build config file will now be dynamically determined

- .build/tasks/Common.Functions.ps1
- .build/tasks/Merge-CodeCoverageFiles.pester.build.ps1
- CHANGELOG.md
- Sampler/Assets/build.yaml.template
- Added the functionality to merge multiple JaCoCo code coverage files into one file. [closes #127]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/128)
> New task: Merge JaCoCo code coverage files

- CONTRIBUTING.md
This change adds a link directly to instructions for how to run unit
and integration tests from the CONTRIBUTING.md file. Prior to this
those instructions were not very discoverable, leaving some contributors
to spend a lot of time figuring out how to get automated tests to run
on their local machines before pushing code up for automated testing.
Fixes #136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/137)
> Link to testing guidelines from Contributing [skip ci]

- CHANGELOG.md
- Sampler/suffix.ps1
- Fixes #161 
- Now the the module does not export the helper function modules as tasks
aliases (issue #161).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/163)
> Does not export the helper function modules as tasks

- .build/tasks/DscResource.Test.build.ps1
- CHANGELOG.md
TITLE: Add check to change parameter name based on Pester Version
With updates to support Pester 5 it was not picking up exceptions for Pester4.
- CI/CD was not picking up skipped rules for HQRM tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/178)
> Fix logic for different parameter name for Pester4

- .build/tasks/New-Release.GitHub.build.ps1
- CHANGELOG.md
- tests/QA/module.tests.ps1
This PR adds support for specifying an alternate name for the trunk branch. This is expected as a parameter passed in `MainGitBranch` and will default to `master` if not specified.
- Added support to use an alternate name for the trunk branch in
`New-Release.GitHub.build.ps1` ([issue #182](https://github.com/gaelcolas/Sampler/issues/182)).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/183)
> Issue #182 - add alternate trunk name support

- CHANGELOG.md
- Sampler/Public/Add-Sample.ps1
- Sampler/Public/New-SampleModule.ps1
- build.yaml
- tests/Unit/Public/Add-Sample.tests.ps1
- tests/Unit/Public/New-SampleModule.tests.ps1
This draft PR is meant to be rebased after #186.
I want to create a few functions so that it's easier to add some sample elements when creating or starting a module.
I'm thinking about the following:
`New-SampleModule` (see prototype in this PR)
`Add-DscClassResource`
`Add-DscMofResource`
`Add-PrivateFunction`
`Add-PublicFunction`
Let me know what you think would be useful.
I'll probably evolve the templates so that the associate tests are optional, so that you can add a component's test with the simple use of a switch to the command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/187)
> adding function wrapping Invoke-Plaster with the templates

- .build/tasks/release.module.build.ps1
- CHANGELOG.md
Attempting to fix the task that pushes the nupkg using Nuget push.
hard to test but it's been failing recently as it looks like nuget command has been added to the AzDO image.
It seems to be a typo issue and also making sure the packing has the right release notes in the PSD1, as we can't "inject" like we do with `Publish-Module`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/194)
> fixing pushing module using nuget push & packing module

- .build/tasks/GuestConfig.build.ps1
- CHANGELOG.md
- Sampler/Public/Add-Sample.ps1
- Sampler/Templates/GCPackage/GCPackages/MyGuestConfigPackage/MyGuestConfigPackage.config.ps1.template
- Sampler/Templates/GCPackage/plasterManifest.xml
- tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1
- Added the build_guestconfiguration_packages task to create GuestConfig packages using the GuestConfiguration module.
- Added GCPackage template so that you can use `Add-Sample -Sample GCPackage` to add a GC Package to your Sampler project.
- Added the gcpack meta task to call clean, build, and build_guestconfiguration_packages for you.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/237)
> Adding task & Sample to build GuestConfig packages

- .build/tasks/Build-Module.ModuleBuilder.build.ps1
- .build/tasks/Clean.ModuleBuilder.build.ps1
- .build/tasks/DeployAll.PSDeploy.build.ps1
- .build/tasks/DscResource.Test.build.ps1
- .build/tasks/Invoke-Pester.pester.build.ps1
- .build/tasks/Merge-CodeCoverageFiles.pester.build.ps1
- .build/tasks/Set-BuildEnvironment.BuildHelpers.build.ps1
- .build/tasks/release.module.build.ps1
- CHANGELOG.md
- Sampler/Public/Get-SamplerAbsolutePath.ps1
- Sampler/Public/Get-SamplerBuiltModuleBase.ps1
- Sampler/Public/Get-SamplerBuiltModuleManifest.ps1
- Sampler/Public/Get-SamplerModuleInfo.ps1
- Sampler/Public/Get-SamplerModuleRootPath.ps1
- build.yaml
- Fixed #247 where Building submodule would fail on linux (but not WSL).
- Fixed #239 to re-add support for BuiltModuleSubdirectory more consistently.
- Refactored a lot of Path resolution into Sampler public function for consitency and re-usability.
- Updated the Tasks to use those Sampler functions.
- Updated Get-BuiltModuleVersion to support $BuiltModuleSubdirectory as per #239.
- Added Get-SamplerAbsolutePath, Get-SamplerBuiltModuleBase, Get-SamplerModuleInfo,
Get-SamplerBuiltModuleManifest, Get-SamplerModuleRootPath.
Once (pre)released here, the `DscResource.DocGenerator` module will have to be updated for its tasks.
There's a small breaking change with `Get-BuiltModuleVersion`.
/cc @johlju
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> updating the path resolution with new sampler public functions and fixing some issues

- .build/tasks/Build-Module.ModuleBuilder.build.ps1
- .build/tasks/DscResource.Test.build.ps1
- .build/tasks/Invoke-Pester.pester.build.ps1
- CHANGELOG.md
as per SharePointDsc, the tasks fails when there's no RootModule in the Module manifest.
```
Built Module Base        = '/home/vsts/work/1/s/output/SharePointDsc/4.6.0'
Built Module Manifest    = '/home/vsts/work/1/s/output/SharePointDsc/4.6.0/SharePointDsc.psd1'
ERROR: Cannot bind argument to parameter 'Path' because it is null.
At /home/vsts/work/1/s/output/RequiredModules/Sampler/0.109.6/tasks/Build-Module.ModuleBuilder.build.ps1:451 char:50
+ … leRootScriptPath = (Get-Item -Path $builtModuleRootScriptPath).FullNa …
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~
At /home/vsts/work/1/s/output/RequiredModules/Sampler/0.109.6/tasks/Build-Module.ModuleBuilder.build.ps1:402 char:1
+ Task Build_DscResourcesToExport_ModuleBuilder {
+ …
```
> fixing issue for Manifest only no builtmoduleRootScriptPath

- .build/tasks/Invoke-Pester.pester.build.ps1
- .build/tasks/Merge-CodeCoverageFiles.pester.build.ps1
- CHANGELOG.md
- azure-pipelines.yml
- build.yaml
- codecov.yml
- Pipeline updated to support merging code coverage between operating
system pipeline jobs.
- Fix uploading to Azure Code Coverage.
- _Merge_CodeCoverage_Files_
- Fixed so the file that is outputted is in UTF-8 (without BOM) to support 
Codecov.io.
- The task now only searches for the file pattern inside the `./output/testResults`
folder.
- The merge process is not attempted if `CodeCoverageThreshold` is set to 
`0`.
- Updated so that build.yaml now have a key `CodeCoverage` which have to
settings `CodeCoverageMergedOutputFile` and `CodeCoverageFilePattern`.
- _Convert_Pester_Coverage_
- The backup file now have the extension `.bak` (instead of `.bak.xml`)
so that is not mistakenly used by a task _Merge_CodeCoverage_Files_.
- Some code cleanup.
---
This change …
> Fix Azure coverage and merge coverage over pipeline jobs

- .build/tasks/Invoke-Pester.pester.build.ps1
- CHANGELOG.md
- Fix task _Convert_Pester_Coverage_ so it is skipped when `CodeCoverageThreshold`
is `0`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/269)
> Convert_Pester_Coverage: Fix task so it is skipped

- CHANGELOG.md
- Resolve-Dependency.ps1
- Sampler/Templates/Build/Resolve-Dependency.ps1
Launched `Resolve-Dependency.ps1` and encountered the following error:
```powershell
PS C:\dev\fork\sampler> .\Resolve-Dependency.ps1
Save-Module : Cannot find the path 'C:\dev\fork\sampler\output\RequiredModules' because it does not exist.
At C:\dev\fork\sampler\Resolve-Dependency.ps1:384 char:13
+             Save-Module @SaveModuleParam
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Save-Module], InvalidOperationException
+ FullyQualifiedErrorId : PathNotFound,Save-Module
```
Searched repo for all `Save-Module` mentions to include the `-Force` switch.
- Resolve-Dependency.ps1: add -Force to all Save-Module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> [Resolve-Dependency.ps1] add -Force to all Save-Module.

- .build/tasks/JaCoCo.coverage.build.ps1
- CHANGELOG.md
- Sampler/Public/Get-CodeCoverageThreshold.ps1
- Sampler/Public/Get-SamplerCodeCoverageOutputFile.ps1
- tests/Unit/Public/Get-CodeCoverageThreshold.tests.ps1
- tests/Unit/Public/Get-SamplerCodeCoverageOutputFile.tests.ps1
- The task _Convert\_Pester\_Coverage_ was changed to support converting
Pester 5 code coverage.
- The task _Convert\_Pester\_Coverage_ was changed to support converting
Pester 5 code coverage.
- The function `Get-CodeCoverageThreshold` was changed to support Pester 5
advanced build configuration.
- The function `Get-SamplerCodeCoverageOutputFile` was changed to support Pester 5
advanced build configuration.
- Fix so that _Convert\_Pester\_Coverage_ correctly replaces build version
with source folder in JaCoCo file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/284)
> Change task Convert_Pester_Coverage to for Pester 5

- CHANGELOG.md
- tests/Unit/Public/Get-BuildVersion.tests.ps1
- Added unit test for public command `Get-BuildVersion`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/286)
> Added unit test for public command `Get-BuildVersion`

- .build/tasks/Invoke-Pester.pester.build.ps1
- CHANGELOG.md
- If the Pester build configuration key `ExcludeFromCodeCoverage` does
not specify a value, the task `Invoke_Pester_Tests_v5` no longer fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/295)
> Fix task `Invoke_Pester_Tests_v5`

- CHANGELOG.md
- Sampler/Templates/Build/build.ps1
- Sampler/scripts/Set-SamplerTaskVariable.ps1
- build.ps1
- Added support of BuiltSubDirectoryDirectory in build configuration files (#299)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/306)
> Added support of BuiltSubDirectoryDirectory in build configuration files (#299)

- CHANGELOG.md
- Sampler/Templates/Build/build.ps1
- Sampler/scripts/Set-SamplerTaskVariable.ps1
- tests/Integration/Tasks/Set-SamplerTaskVariable.Tests.ps1
Fixe issue #299 and correct PR #306. 
- Removed `$BuiltModuleSubdirectory` definition in the `begin` bloc of `build.ps1`
template ([issue #299](https://github.com/gaelcolas/Sampler/issues/299)).
- Added pester tests for Set-SamplerTaskVariable.ps1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/310)
> Fixe issue #299 and correct PR #306

- CHANGELOG.md
- Sampler/Templates/Sampler/plasterManifest.xml
None
- Changed Plaster Template (`Sampler/Templates/Sampler/plasterManifest.xml`), so
that all functions will be exported by default, which in turn correlates with
the template code in `Sampler/Sampler.psm1`, which uses
`Export-ModuleMember` to export all functions loaded from the
`Public` (sub-)folder.
None
None
None
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/312)
> Allow all public functions to be exported from generated PSD1 file per default.

- .build/tasks/release.module.build.ps1
- CHANGELOG.md
Building a module with a `$BuiltModuleSubdirectory` was failing on the `pack` task because it was not updated to use $BuiltModuleBase (that derives from `$builtmodulesubdirectory`).
/cc @NicolasBn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/313)
> fixing builtmoduleSubdirectory issue

- .build/tasks/Invoke-Pester.pester.build.ps1
- CHANGELOG.md
- Task `Pester_If_Code_Coverage_Under_Threshold`
- Now the code code coverage threshold is correctly reported using decimals.
Fixes #302 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/317)
> Pester_If_Code_Coverage_Under_Threshold: Correctly reports coverage percentage

- .build/tasks/release.module.build.ps1
- CHANGELOG.md
- Sampler/scripts/Set-SamplerTaskVariable.ps1
- Making sure the `Set-SamplerTaskVariable` does not fail when there's no Module manifest (i.e. when using Sampler for other reasons than building a module).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/331)
> Don't fail when there's no project name 

- .build/tasks/GuestConfig.build.ps1
- CHANGELOG.md
- Fixed GuestConfiguration compilation to work with GuestConfiguration module version 4.0.0-preview0002.
- Set the default type to AuditAndSet, but supporting override by creating a '$GCPackageName.psd1' file along with the config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/338)
> fixing gc pol compilation to work with latest version of GC module

- CHANGELOG.md
- Sampler/Public/Get-SamplerAbsolutePath.ps1
- fix #341
Fixes #341
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/342)
> 'Get-SamplerAbsolutePath' may return wrong path

- CHANGELOG.md
- Sampler/Templates/Build/build.yaml.template
- build.yaml
- The templates was using the task `Create_ChangeLog_GitHub_PR` in the meta task
publish that is also specifically run in a separate Azure Pipelines task. This
made the task to run twice.
Fixes #339 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/340)
> Fix duplicate run of task `Create_ChangeLog_GitHub_PR`

- .build/tasks/Invoke-Pester.pester.build.ps1
- CHANGELOG.md
- When running test using Pester 5, and the build configuration (`build.yaml`)
do not specify the location of tests in the key `Path`, the pipeline will
no longer run the tests twice. Fixes [#337](https://github.com/gaelcolas/Sampler/issues/337)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/347)
> No longer run Pester 5 tests twice when missing key `Path`

- CHANGELOG.md
- Sampler/Templates/Build/build.ps1
- build.ps1
- explicit parameter value in 'build.ps1' while calling 'Resolve-Dependency.ps1'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/352)
> Fixed explicit parameter value in 'build.ps1' while calling 'Resolve-Dependency.ps1'

- .build/tasks/Invoke-Pester.pester.build.ps1
- CHANGELOG.md
- The task `Invoke_Pester_Tests_v5` generated a unexpected filename for the
test results, compared to the Pester 4 task. Fixes [#355](https://github.com/gaelcolas/Sampler/issues/355)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/356)
> Fix test result filename in task `Invoke_Pester_Tests_v5`

- .build/tasks/GuestConfig.build.ps1
- CHANGELOG.md
- GuestConfiguration build task on MOF file name equal to 'localhost.mof'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/353)
> Fixed GuestConfiguration build task on MOF file name equal to 'localhost.mof'

- .build/tasks/Invoke-Pester.pester.build.ps1
- CHANGELOG.md
- build.yaml
- New task `Pester_Run_Times` that outputs each test's run time. Only works
for Pester 5. The task will be skipped if Pester 4 is used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/363)
> Add task `Pester_Run_Times`

- .build/tasks/release.module.build.ps1
- CHANGELOG.md
- Task `package_module_nupkg` now correctly adds the release notes to the
Nuget package. Fixes [#373](https://github.com/gaelcolas/Sampler/issues/373)
- Task `publish_module_to_gallery` now correctly adds the release notes to
the published module. Fixes [#373](https://github.com/gaelcolas/Sampler/issues/373)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/374)
> Fix release notes for published module

- CHANGELOG.md
- Sampler/scripts/Set-SamplerTaskVariable.ps1
- tests/Unit/TestHelpers/MockSetSamplerTaskVariable.ps1
- tests/Unit/tasks/Build-Module.ModuleBuilder.build.Tests.ps1
- `Set-SamplerTaskVariable`
- Reverted code that was removed in pull request #383. The code is
necessary because how the commands `Get-BuiltModuleVersion`,
`Get-SamplerBuiltModuleManifest`, `Get-SamplerBuiltModuleBase`, and 
`Get-SamplerModuleRootPath` are currently built. The code that was
reverted handles resolving the wildcard (`*`) in the returned paths
from the mentioned commands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/391)
> Fix bug introduced with PR #383

- CHANGELOG.md
- Sampler/Templates/Sampler/module.tests.ps1.template
- tests/QA/module.tests.ps1
This PR almost only applies this project's code style rules to the file `\tests\QA\module.tests.ps1`. The only functional change is making use of the variable `$ProjectName` instead of using the hard coded name `Sampler`.
The file `\Sampler\Templates\Sampler\module.tests.ps1.template` was synced with `\tests\QA\module.tests.ps1` as the file `module.tests.ps1.template` still used the Pester 4 syntax and simply does not work with new modules.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/396)
> Fixing code style `module.tests.ps1`

- CHANGELOG.md
- Resolve-Dependency.ps1
- Sampler/Templates/Build/Resolve-Dependency.ps1
Fixes #394: When having AllowPrerelease set to $true in Resolve-Dependency.psd1, this setting is ignored.
- #394
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/395)
> Fixes #394

- CHANGELOG.md
- Sampler/Templates/Build/RequiredModules.psd1.template
When creating a module with `ModuleType` `CompleteModule`, `RequiredModules.psd1` is incomplete
- Fixes #397, `ModuleType` Plaster parameter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/398)
> Fixes #397

- CHANGELOG.md
- tests/Unit/Public/Get-MofSchemaName.tests.ps1
- `Get-MofSchemaName`
- Permanently skipped a test that the build worker `ubuntu-latest` were
unable to run due to missing shared library 'libmi'.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/406)
> Fix test issue with build worker ubuntu-latest

- .build/tasks/JaCoCo.coverage.build.ps1
- CHANGELOG.md
- tests/Unit/tasks/JaCoCo.coverage.build.Tests.ps1
- Task `Convert_Pester_Coverage`
- No longer throws an exception when there was just one missed command
for a test suite. Fixes [#407](https://github.com/gaelcolas/Sampler/issues/407).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/408)
> `Convert_Pester_Coverage`: No longer throws an exception

- CHANGELOG.md
- Sampler/Templates/Sampler/module.tests.ps1.template
- tests/QA/module.tests.ps1
- The QA tests can now be debugged by `Invoke-Pester` directly, before it
had to be started by the build script `build.ps1`. This will also help
the Pester Tests VS Code extension to be able to run the tests.
- Now the QA test that verifies that the Unreleased section header is present
in the CHANGELOG.md correctly supports ChangelogManagement v3.0.1.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/sampler/405)
> Fix QA test for ChangelogManagement v3.0.1

- CHANGELOG.md
- CONTRIBUTING.md
- Resolve-Dependency.ps1
- Sampler/Templates/Build/CONTRIBUTING.md
- Sampler/Templates/Build/Resolve-Dependency.ps1
- Sampler/suffix.ps1
- Pipeline script for resolving dependencies improved.
- Evaluating PowerShellGet version now supports parameter `AllowOldPowerShellGetModule`
(still not recommended to use this parameter).
- Now defaults to save the modules PowerShellGet and PackageManagement
to the folder `output/RequiredModules` (same logic as for module PSDepend)
to not make permanent changes to the contributors machine. If parameter
`PSDependTarget` is either set to `CurrentUser` or `AllUsers` the modules
are installed.
- Updated text in the CONTRIBUTING.md to help contributors more easily find
a guide where to start.
- Pipeline script for resolving dependencies improved.
- `Get-PackageProvider` no longer throws an exception when NuGet provider
is missing (in Windows PowerShell in a clean Windows install).
- …
> Improve script `Resolve-Dependency.ps1`

- .build/tasks/release.module.build.ps1
- CHANGELOG.md
- tests/Unit/tasks/release.module.build.Tests.ps1
Adds support for publishing a NuGet package with the .NET SDK, if installed.
Fixes [433](https://github.com/gaelcolas/Sampler/issues/433).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/434)
> feat: Add support for publishing NuGet package with .NET SDK

- CHANGELOG.md
- README.md
- Resolve-Dependency.ps1
- Resolve-Dependency.psd1
- Sampler/Templates/Build/Resolve-Dependency.ps1
- Sampler/Templates/Build/Resolve-Dependency.psd1.template
- Sampler/Templates/Build/build.ps1
- build.ps1
- tests/Integration/ResolveDependencies.Integration.Tests.ps1
- Support for [PSResourceGet (beta release)](https://github.com/PowerShell/PSResourceGet).
If the modules PSResourceGet can be bootstrapped they will be used. If
PSResourceGet cannot be bootstrapped then it will revert to using
PowerShellGet v2.2.5. If the user requests or configures to use ModuleFast
then that will override both PSResourceGet and PowerShellGet. The method
PSResourceGet can be enabled in the configuration file Resolve-Dependency.psd1.
It is also possible to use PSResourceGet by adding the parameter `UsePSResourceGet`
to the `build.ps1`, e.g. `./build.ps1 -Tasks noop -ResolveDependency -UsePSResourceGet`.
- When using PSResourceGet to resolve dependencies it also possible to
use PowerShellGet v2.9.0 (previous _CompatPowerShellGet_). To use the
compatibility module it can …
> Support for PSResourceGet

- CHANGELOG.md
- Sampler/scripts/Set-SamplerTaskVariable.ps1
After a few hours debugging in DscResource.DocGenerator I found that it was this bug that cause the other variables not to be set to correct values, or no mocks was hit as I was expecting. 🙂 Now off to holiday celebration. 🎄 
- Now the tasks work when using `Set-SamplerTaskVariable` with tasks that
do not have the parameter `ChocolateyBuildOutput`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/454)
> Fix bug when `$ChocolateyBuildOutput` is null or empty string

- CHANGELOG.md
- README.md
- RequiredModules.psd1
- Resolve-Dependency.ps1
- Resolve-Dependency.psd1
- Sampler/Templates/Build/RequiredModules.psd1.template
- Sampler/Templates/Build/Resolve-Dependency.ps1
- Sampler/Templates/Build/Resolve-Dependency.psd1.template
- build.yaml
- ModuleFast now supports resolving individual pre-release dependencies
that is part of _RequiredModules.psd1_. This only works when setting the
parameter value `ModuleFastBleedingEdge` to `$true` in the configuration
file _Resolve-Dependencies.psd1_. When `ModuleFastBleedingEdge` is enabled
it is also possible to specify [NuGet version ranges](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges)
in _RequiredModules.psd1_, although then the file is not compatible with
PSResourceGet or PSDepend (so no fallback can happen).
- Update PSResourceGet to default to v1.0.1 if no version is passes in parameter
or specific version is configured.
- Templates was changed to use PSResourceGet as the default method
of resolving dependencies. It is possible to change to …
> Support prerelease with ModuleFast and make PSResourceGet the default method

- .build/tasks/release.module.build.ps1
- CHANGELOG.md
- Resolve-Dependency.psd1
- azure-pipelines.yml
- Switch to build worker `windows-latest` for the build phase of the pipeline
due to a issue using `Publish-Module` on the latest updated build worker in
Azure Pipelines.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/464)
> Switch image for pipeline build phase

- CHANGELOG.md
- Sampler/Templates/Sampler/azure-pipelines.yml.template
- Sampler/Templates/Sampler/azure-pipelines_dsccommunity.yml.template
- azure-pipelines.yml
- Pinned GitVersion to v5 in the pipeline since v6 is not yet supported, also
updated templates to pin GitVersion v5. Workaround for issue [#477](https://github.com/gaelcolas/Sampler/issues/477).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/479)
> Pin GitVersion to v5 in pipeline and update templates

- CHANGELOG.md
- Resolve-Dependency.ps1
- Sampler/Templates/Build/Resolve-Dependency.ps1
This fixes #519 by using a full-qualified call to `Expand-Archive`.
- Using full-qualified call for `Expand-Archive` ([#519](https://github.com/gaelcolas/Sampler/issues/519)).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gaelcolas/Sampler/524)
> Fixes #519: Use fully-qualified call for `Expand-Archive`
